project_id = "ylsknodothsvuzpvfsaf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.parse-resume]
verify_jwt = false

[functions.analyze-job]
verify_jwt = false

[functions.tailor-resume]
verify_jwt = false

[functions.generate-export]
verify_jwt = false

[functions.generate-content]
verify_jwt = false

[functions.cleanup-guest-data]
verify_jwt = false