// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylsknodothsvuzpvfsaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlsc2tub2RvdGhzdnV6cHZmc2FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1Mjk1MTAsImV4cCI6MjA3NDEwNTUxMH0.yLA_0zi_gSNhm8R1hy6Y1fvUQJavwAR8rRZDat4J52A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});